name: saaf
description: Native relevant student ads
version: 0.0.1
homepage: https://github.com/statsfm/saaf-dart-gemairo
repository: https://github.com/statsfm/saaf-dart-gemairo
issue_tracker: https://github.com/statsfm/saaf-dart-gemairo/issues
documentation: https://github.com/statsfm/saaf-dart-gemairo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^1.1.0
  url_launcher: ^6.1.8
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
